#pragma once

#include <Arduino.h>

static const char kStringsPlJson[] PROGMEM = R"JSON({
  "pageTitle": "ESP32-CAM",
  "cameraAlt": "Podgląd z ESP32-CAM",
  "buttonLedToggle": "Włącz/wyłącz LED",
  "buttonFullscreen": "Pełny ekran",
  "buttonExitFullscreen": "Wyjdź z pełnego ekranu",
  "buttonApplyImage": "Zastosuj obraz",
  "buttonTakeover": "Przejmij kamerę",
  "buttonSwitchLanguage": "English",
  "buttonSwitchLanguageAria": "Zmień język",
  "labelResolution": "Rozdzielczość",
  "optionLow": "Niska",
  "optionMedium": "Średnia",
  "optionHigh": "Wysoka",
  "ledStateOn": "ON",
  "ledStateOff": "OFF",
  "statusActiveTemplate": "Transmisja aktywna. Jesteś aktywnym oglądającym. Aktywność: {lagMs} ms. LED: {led}.",
  "overlayCameraOfflineRetry": "Kamera offline. Próba ponownego połączenia...",
  "statusCameraOfflineWait": "Kamera offline. Czekam na powrót połączenia...",
  "overlayCameraBackOnline": "Kamera wróciła online. Łączenie...",
  "statusCameraBackOnline": "Kamera wróciła online. Trwa łączenie...",
  "statusSessionTaken": "Sesja została przejęta przez innego użytkownika.",
  "overlaySessionTakenTakeover": "Twoja sesja została przejęta przez innego użytkownika. Kliknij przycisk, aby przejąć kamerę.",
  "statusCameraBusy": "Kamera jest aktualnie zajęta przez innego użytkownika.",
  "overlayCameraBusyTakeover": "Kamera jest aktualnie używana przez innego klienta. Kliknij przycisk, aby przejąć kamerę.",
  "overlayNoFramesRecover": "Brak nowych klatek. Przywracam transmisję...",
  "statusSessionInactiveRetake": "Sesja nieaktywna. Przejmuję obraz ponownie...",
  "overlayLikelyBusy": "Prawdopodobnie ktoś używa kamerki.",
  "statusStreamRestoreFailed": "Nie udało się przywrócić transmisji.",
  "overlayRestoringStream": "Przywracam transmisję...",
  "statusStreamProblemReconnect": "Wykryto problem z transmisją. Trwa ponowne łączenie...",
  "statusStabilizingSession": "Stabilizuję sesję na serwerze. Ponawiam...",
  "statusTakeoverButtonOnly": "Kamera zajęta. Przejęcie tylko po kliknięciu przycisku.",
  "overlayTakeoverRetryPrompt": "Kamera jest aktualnie używana przez innego klienta. Kliknij, aby przejąć ponownie.",
  "statusTakeoverRetryTemplate": "Przejęcie nieudane. Spróbuj ponownie za około {retryMs} ms.",
  "overlayConnectingCamera": "Łączenie z kamerą...",
  "statusConnectingCamera": "Łączenie z kamerą...",
  "statusWeakSignalReconnect": "Słaby sygnał. Ponawiam połączenie z kamerą...",
  "overlayStartImageFailed": "Nie udało się uruchomić obrazu. Kliknij przycisk, aby przejąć kamerę.",
  "statusDeviceBusyOrWeakSignal": "Urządzenie zajęte lub słaby sygnał. Kliknij przycisk.",
  "overlayUsedByAnotherClient": "Kamera jest aktualnie używana przez innego klienta.",
  "overlayChangingImageSettings": "Zmieniam ustawienia obrazu...",
  "statusStreamStillStopping": "Poczekaj chwilę, strumień jeszcze się zatrzymuje.",
  "statusCameraBusyByOther": "Kamera jest zajęta przez innego klienta.",
  "statusImageSettingsChangeFailed": "Nie udało się zmienić ustawień obrazu.",
  "statusImageSettingsSaved": "Ustawienia obrazu zapisane.",
  "statusNetworkErrorChangingImage": "Błąd sieci podczas zmiany ustawień obrazu.",
  "overlayCameraUnavailableTakeover": "Kamera jest zajęta lub niedostępna. Kliknij przycisk, aby przejąć kamerę.",
  "statusTakeoverOnlyByButton": "Przejęcie działa tylko po kliknięciu przycisku.",
  "overlayTakingOverCamera": "Przejmuję kamerę...",
  "statusTakingOverCamera": "Próba przejęcia kamery..."
})JSON";
