#pragma once

#include <Arduino.h>

static const char kStringsEnJson[] PROGMEM = R"JSON({
  "pageTitle": "ESP32-CAM",
  "cameraAlt": "ESP32-CAM preview",
  "buttonLedToggle": "Toggle LED",
  "buttonFullscreen": "Fullscreen",
  "buttonExitFullscreen": "Exit fullscreen",
  "buttonApplyImage": "Apply image",
  "buttonTakeover": "Take over camera",
  "buttonSwitchLanguage": "Polski",
  "buttonSwitchLanguageAria": "Switch language",
  "labelResolution": "Resolution",
  "optionLow": "Low",
  "optionMedium": "Medium",
  "optionHigh": "High",
  "ledStateOn": "ON",
  "ledStateOff": "OFF",
  "statusActiveTemplate": "Stream active. You are the active viewer. Activity: {lagMs} ms. LED: {led}.",
  "overlayCameraOfflineRetry": "Camera offline. Retrying connection...",
  "statusCameraOfflineWait": "Camera offline. Waiting for connection to return...",
  "overlayCameraBackOnline": "Camera is back online. Connecting...",
  "statusCameraBackOnline": "Camera is back online. Connecting...",
  "statusSessionTaken": "Your session was taken over by another user.",
  "overlaySessionTakenTakeover": "Your session was taken over by another user. Click the button to take over the camera.",
  "statusCameraBusy": "Camera is currently busy with another user.",
  "overlayCameraBusyTakeover": "Camera is currently used by another client. Click the button to take over the camera.",
  "overlayNoFramesRecover": "No new frames. Restoring stream...",
  "statusSessionInactiveRetake": "Session inactive. Reclaiming stream...",
  "overlayLikelyBusy": "The camera is likely in use by someone else.",
  "statusStreamRestoreFailed": "Could not restore stream.",
  "overlayRestoringStream": "Restoring stream...",
  "statusStreamProblemReconnect": "Stream issue detected. Reconnecting...",
  "statusStabilizingSession": "Stabilizing session on server. Retrying...",
  "statusTakeoverButtonOnly": "Camera busy. Takeover only after clicking the button.",
  "overlayTakeoverRetryPrompt": "Camera is currently used by another client. Click to try takeover again.",
  "statusTakeoverRetryTemplate": "Takeover failed. Try again in about {retryMs} ms.",
  "overlayConnectingCamera": "Connecting to camera...",
  "statusConnectingCamera": "Connecting to camera...",
  "statusWeakSignalReconnect": "Weak signal. Reconnecting to camera...",
  "overlayStartImageFailed": "Could not start video. Click the button to take over the camera.",
  "statusDeviceBusyOrWeakSignal": "Device busy or weak signal. Click the button.",
  "overlayUsedByAnotherClient": "Camera is currently used by another client.",
  "overlayChangingImageSettings": "Changing image settings...",
  "statusStreamStillStopping": "Please wait, stream is still stopping.",
  "statusCameraBusyByOther": "Camera is busy with another client.",
  "statusImageSettingsChangeFailed": "Could not change image settings.",
  "statusImageSettingsSaved": "Image settings saved.",
  "statusNetworkErrorChangingImage": "Network error while changing image settings.",
  "overlayCameraUnavailableTakeover": "Camera is busy or unavailable. Click the button to take over the camera.",
  "statusTakeoverOnlyByButton": "Takeover works only after clicking the button.",
  "overlayTakingOverCamera": "Taking over camera...",
  "statusTakingOverCamera": "Attempting camera takeover..."
})JSON";
